<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.0.9</Version>
        <PackageId>Bounteous.xUnit.Accelerator</PackageId>
        <Authors>Bounteous</Authors>
        <Company>Bounteous</Company>
        <LicenseExpression>MIT</LicenseExpression>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Bounteous.Core" Version="0.0.23" />
      <PackageReference Include="Bounteous.Data" Version="0.0.31" />
      <PackageReference Include="Moq" Version="4.20.72" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="docs\README.md" />
      <Content Include="docs\README.md">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <None Update="docs/README.md" Pack="true" PackagePath="" />
    </ItemGroup>    
    
</Project>
